version: "3.8"
services: 
  frontend: 
    container_name: frontend
    build: ./frontend
    depends_on: 
      - backend
    ports: 
      - 4200:80
    networks: 
      - network-backend   
  backend: 
    build: ./backend
    container_name: backend
    volumes:
      - D:\KPI\7_semester\IPZ\lab5:/app/images
    depends_on: 
      - mongo
      - postgres
    ports: 
      - 8080:8080
    networks: 
      - network-backend   

  mongo: 
    image: mongo
    restart: always
    container_name: mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    command: ["mongod"]  
    ports: 
      - 27018:27017
    networks: 
      - network-backend   
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lab4_postgres
    ports: 
      - 5433:5432
    networks: 
      - network-backend   

networks: 
  network-backend:

 